### ISSUE TITLE
The example code does not seem to do anything, when you press search nothing happens.

### ISSUE THREAD

**Issue by RogierWijsman** [devbolcom/bolcom-jqueryopensearch-js-example#1]

**Comment by RogierWijsman** [comment]
The example code does not seem to do anything, when you press search nothing happens.

**Comment by derkmdt** [comment]
Hi Rogier,

Seems to be going wrong since they moved some pages on the site. Here is the working example: https://developers.bol.com/examples/jqueryexamplecodeopensearch/
